### ISSUE TITLE
createDummyGenerator throws errors in 1.7.1

### ISSUE THREAD

**Issue by romanlv** [yeoman/yeoman-test#42]
Works fine in `1.7.0`, but in `1.7.1` 

```
const helpers = require("yeoman-test");

...
    mockery.registerMock(require.resolve("..."), helpers.createDummyGenerator());
```

throws `TypeError: Generator.extend is not a function`

see full [example](https://github.com/electrode-io/electrode/blob/736c3a4e7f3f03db78777f8eab047364db69336b/packages/generator-electrode/test/spec/app.spec.js#L24)

**Comment by SBoudrias** [comment]
Latest release should be fixed.

The issue is that gulp is swallowing all our errors now on CI... Not sure what we messed up, might just be a careless upgrade. We should fix eventually by getting rid of gulp altogether and following the new `generator-node` standard process.
